/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package fm.last.android;

public final class R {
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int unknownImage=0x7f010000;
    }
    public static final class drawable {
        public static final int action_remove=0x7f020000;
        public static final int album_info=0x7f020001;
        public static final int albumart_mp_unknown=0x7f020002;
        public static final int artist_info=0x7f020003;
        public static final int background_frame_portrait=0x7f020004;
        public static final int btn_media_player=0x7f020005;
        public static final int btn_media_player_disabled=0x7f020006;
        public static final int btn_media_player_disabled_selected=0x7f020007;
        public static final int btn_media_player_pressed=0x7f020008;
        public static final int btn_media_player_selected=0x7f020009;
        public static final int frame=0x7f02000a;
        public static final int full_dark_bg=0x7f02000b;
        public static final int halfrounded_bg=0x7f02000c;
        public static final int ic_menu_friend_list=0x7f02000d;
        public static final int ic_menu_search=0x7f02000e;
        public static final int ic_menu_view_profile=0x7f02000f;
        public static final int ic_mp_album_playback=0x7f020010;
        public static final int ic_mp_artist_playback=0x7f020011;
        public static final int ic_mp_current_playlist_btn=0x7f020012;
        public static final int ic_mp_move=0x7f020013;
        public static final int ic_mp_song_playback=0x7f020014;
        public static final int icon=0x7f020015;
        public static final int icon_ban=0x7f020016;
        public static final int icon_love=0x7f020017;
        public static final int lastfm_button_bg=0x7f020018;
        public static final int lastfm_button_transparent_bg32=0x7f020019;
        public static final int lastfm_button_transparent_bg48=0x7f02001a;
        public static final int lastfm_logo=0x7f02001b;
        public static final int lastfm_revolution=0x7f02001c;
        public static final int media_playback_pause=0x7f02001d;
        public static final int media_playback_start=0x7f02001e;
        public static final int media_seek_forward=0x7f02001f;
        public static final int picture_unknown_3=0x7f020020;
        public static final int playback_seekbar=0x7f020021;
        public static final int playlist_icon=0x7f020022;
        public static final int playlist_top_bg=0x7f020023;
        public static final int profile_unknown=0x7f020024;
        public static final int progress_horizontal=0x7f020025;
        public static final int progress_indeterminate_horizontal=0x7f020026;
        public static final int progressbar_indeterminate1=0x7f020027;
        public static final int progressbar_indeterminate2=0x7f020028;
        public static final int progressbar_indeterminate3=0x7f020029;
        public static final int radio_icon=0x7f02002a;
        public static final int red_bold_radial_gradient32=0x7f02002b;
        public static final int red_bold_radial_gradient48=0x7f02002c;
        public static final int red_circle=0x7f02002d;
        public static final int red_radial_gradient32=0x7f02002e;
        public static final int red_radial_gradient48=0x7f02002f;
        public static final int rounded_bg=0x7f020030;
        public static final int rounded_bg_pressed=0x7f020031;
        public static final int rounded_bg_pressed_fade=0x7f020032;
        public static final int rounded_bg_selected=0x7f020033;
        public static final int stat_notify_musicplayer=0x7f020034;
    }
    public static final class id {
        public static final int album=0x7f060000;
        public static final int albumname=0x7f060002;
        public static final int artistname=0x7f060001;
        public static final int ban=0x7f060008;
        public static final int buttonSetup=0x7f06001c;
        public static final int cancel=0x7f060019;
        public static final int currenttime=0x7f060004;
        public static final int home=0x7f06000a;
        public static final int home_main_list=0x7f060012;
        public static final int home_newstation=0x7f060010;
        public static final int home_profileimage=0x7f06000c;
        public static final int home_songsplayed=0x7f06000f;
        public static final int home_startnewstation=0x7f060011;
        public static final int home_top=0x7f06000b;
        public static final int home_usersname=0x7f06000e;
        public static final int icon=0x7f060016;
        public static final int label=0x7f060015;
        public static final int list_header_title=0x7f060013;
        public static final int login=0x7f06001a;
        public static final int loginLayout=0x7f06000d;
        public static final int love=0x7f060005;
        public static final int main_logo=0x7f06001d;
        public static final int next=0x7f060007;
        public static final int password=0x7f060018;
        public static final int pause=0x7f060006;
        public static final int station_editbox=0x7f060023;
        public static final int station_layout=0x7f06001e;
        public static final int station_list=0x7f060025;
        public static final int station_list_row=0x7f060014;
        public static final int station_search=0x7f060024;
        public static final int station_type_artist=0x7f060020;
        public static final int station_type_tag=0x7f060021;
        public static final int station_type_user=0x7f060022;
        public static final int station_typegroup=0x7f06001f;
        public static final int totaltime=0x7f060009;
        public static final int trackname=0x7f060003;
        public static final int username=0x7f060017;
        public static final int widget45=0x7f06001b;
    }
    public static final class layout {
        public static final int audio_player=0x7f030000;
        public static final int audio_player_common=0x7f030001;
        public static final int home=0x7f030002;
        public static final int list_header=0x7f030003;
        public static final int list_row=0x7f030004;
        public static final int login=0x7f030005;
        public static final int main=0x7f030006;
        public static final int newstation=0x7f030007;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int durationformat=0x7f040012;
        public static final int home_logout=0x7f040006;
        public static final int home_mylibrary=0x7f04000c;
        public static final int home_myloved=0x7f04000b;
        public static final int home_myneighborhood=0x7f04000a;
        public static final int home_myrecs=0x7f040009;
        public static final int home_mystations=0x7f04000d;
        public static final int home_newstation=0x7f040008;
        public static final int home_recentstations=0x7f04000e;
        public static final int home_tracksplayed=0x7f040007;
        public static final int main_cancel=0x7f040003;
        public static final int main_login=0x7f040004;
        public static final int main_password=0x7f040002;
        public static final int main_setup=0x7f040005;
        public static final int main_user=0x7f040001;
        public static final int newstation_artist=0x7f04000f;
        public static final int newstation_tag=0x7f040010;
        public static final int newstation_user=0x7f040011;
    }
    public static final class style {
        public static final int Home=0x7f05000b;
        public static final int Home_ListHeaders=0x7f05000e;
        public static final int Home_NumberPlayed=0x7f05000d;
        public static final int Home_UserName=0x7f05000c;
        public static final int InfoButton=0x7f05000f;
        public static final int LastFMButton=0x7f050002;
        public static final int LastFMButton_Album=0x7f050011;
        public static final int LastFMButton_Artist=0x7f050010;
        public static final int LastFMButton_Ban=0x7f050005;
        public static final int LastFMButton_Logout=0x7f05000a;
        public static final int LastFMButton_Love=0x7f050004;
        public static final int LastFMButton_NewStation=0x7f050009;
        public static final int LastFMButton_Next=0x7f050008;
        public static final int LastFMButton_Pause=0x7f050007;
        public static final int LastFMButton_Play=0x7f050006;
        public static final int LastFMProgressBar=0x7f050003;
        public static final int PlaybackInfo=0x7f050000;
        public static final int PlaybackText=0x7f050001;
    }
    public static final class styleable {
        /** Attributes that can be used with a AlbumView.
           <p>Includes the following attributes:</p>
           <table border="2" width="85%" align="center" frame="hsides" rules="all" cellpadding="5">
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute<th>Summary</tr>
           <tr><th><code>{@link #AlbumView_unknownImage fm.last.android:unknownImage}</code><td></tr>
           </table>
           @see #AlbumView_unknownImage
         */
        public static final int[] AlbumView = {
            0x7f010000
        };
        /**
          <p>This symbol is the offset where the {@link fm.last.android.R.attr#unknownImage}
          attribute's value can be found in the {@link #AlbumView} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:unknownImage
        */
        public static final int AlbumView_unknownImage = 0;
    };
}
